CREATE TABLE TRANSMITTER (
  TRANSMITTER_ID INTEGER(7),
  PASSWORD_CODE INTEGER(6),
  CURRENT_INDEX INTEGER,
  CONSTRAINT PK_TRANSMITTER PRIMARY KEY (TRANSMITTER_ID,PASSWORD_CODE)
)
ENGINE = InnoDB;

CREATE TABLE TRANSMITTER_DATA (
  TRANSMITTER_ID INTEGER(7),
  PASSWORD_CODE INTEGER(6),
  DATA_INDEX INTEGER,
  DATA_TIME INTEGER,
  RAW_VALUE INTEGER(6),
  FILTERED_VALUE INTEGER(6),
  DEX_BATTERY INTEGER(3),
  PREV_TIME INTEGER,
  BATTERY_PERC INTEGER(3),
  BATTERY_MVOLT INTEGER(4),
  CPU_TEMP INTEGER(4),
  GEOLOCATION VARCHAR(21),
  CONSTRAINT PK_TRANSMITTER_DATA PRIMARY KEY (TRANSMITTER_ID,PASSWORD_CODE,DATA_INDEX),
  CONSTRAINT FK_TRANSMITTER_DATA FOREIGN KEY (TRANSMITTER_ID,PASSWORD_CODE) REFERENCES TRANSMITTER (TRANSMITTER_ID,PASSWORD_CODE)
)
ENGINE = InnoDB;

  
